
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: billing_development
  host: localhost

test:
  <<: *default
  database: billing_test

production:
  <<: *default
  database: billing_production
  username: billing
  password: <%= ENV['BILLING_DATABASE_PASSWORD'] %>
